### ISSUE TITLE
Seeing "utils.js:2 Uncaught Error: Cannot find module 'crypto'"

### ISSUE THREAD

**Issue by soichih** [okta/okta-jwt-verifier-js#35]
### Describe the bug

Hello. 

I just did npm install of this module and now I am seeing the following error message.

```
utils.js:2 Uncaught Error: Cannot find module 'crypto'
    at webpackMissingModule (utils.js:2:1)
    at ./node_modules/jwks-rsa/src/utils.js (utils.js:2:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./node_modules/jwks-rsa/src/JwksClient.js (JwksClient.js:2:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./node_modules/jwks-rsa/src/index.js (index.js:1:1)
```

### Reproduction Steps?

```
import OktaJwtVerifier from '@okta/jwt-verifier';

const oktaJwtVerifier = new OktaJwtVerifier({
     issuer: `${config.OKTA_URL}/oauth2/default`
})

oktaJwtVerifier.verifyAccessToken(token, expected_aud);
```

### SDK Versions

  System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (16) x64 Intel(R) Xeon(R) Platinum 8375C CPU @ 2.90GHz
    Memory: 50.99 GB / 61.79 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 19.3.0 - /usr/bin/node
    npm: 9.2.0 - /usr/bin/npm
  Browsers:
    Chromium: 115.0.5790.170

**Comment by jaredperreault-okta** [comment]
I tested installation on a few versions of node, no issues:

```bash
jared:foobar$ npm --version
6.14.17
jared:foobar$ node --version
v14.20.1
jared:foobar$ npm i @okta/jwt-verifier
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.

+ @okta/jwt-verifier@3.0.1
added 28 packages from 105 contributors and audited 28 packages in 0.958s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

```bash
jared:foobar$ node --version
v19.9.0
jared:foobar$ npm --version
9.6.3
jared:foobar$ npm i @okta/jwt-verifier

added 28 packages, and audited 29 packages in 2s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

From the stack trace, it seems like you're using webpack - Can you elaborate on your use case? This module is only meant to run in a node context

**Comment by michaau90** [comment]
The problem occurs for webpack 5

**Comment by jaredperreault-okta** [comment]
@michaau90 Can you explain your use case and ideally provide a webpack config?
